version: '3.7'

services:
   hls_server:
    container_name: hls_server
    build:
      context: .
      dockerfile: Dockerfile

    restart: always
    networks:
      - red
    ports:
      - "1935:1935" 
      - "80:8080"
    volumes:
      - ./app:/usr/local/nginx/html:ro
      - ./config:/usr/local/nginx/conf/

networks:
  red:
    driver: bridge
